language: "ruby"
rvm:
  - "2.6.3"
before_script:
  - "bundle install"
script:
  - "bundle exec jekyll build"
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
cache: bundler
notifications:
  email: false
