name: "The Black Unicorn"
logo: "/assets/images/logo/logo.svg"
menuTitle: "Menu"
description: "My personal website."

57x57: "/assets/images/favicon/apple-icon-57x57.png"
60x60: "/assets/images/favicon/apple-icon-60x60.png"
72x72: "/assets/images/favicon/apple-icon-72x72.png"
76x76: "/assets/images/favicon/apple-icon-76x76.png"
114x114: "/assets/images/favicon/apple-icon-114x114.png"
120x120: "/assets/images/favicon/apple-icon-120x120.png"
144x144: "/assets/images/favicon/apple-icon-144x144.png"
152x152: "/assets/images/favicon/apple-icon-152x152.png"
180x180: "/assets/images/favicon/apple-icon-180x180.png"
192x192: "/assets/images/favicon/android-icon-192x192.png"
32x32: "/assets/images/favicon/favicon-32x32.png"
96x96: "/assets/images/favicon/favicon-96x96.png"
16x16: "/assets/images/favicon/favicon-16x16.png"
manifest: "/assets/images/favicon/manifest.json"
144x144: "/assets/images/favicon/ms-icon-144x144.png"
styles: "/assets/css/styles.css"
javascript: "/assets/javascript/nav.js"

baseurl: "/"
url: "https://iamtheblackunicorn.github.io"
plugins:
  - jekyll-feed
